### PR TITLE
ci: move to final release of 3.11

### PR DESCRIPTION
**Pull request by henryiii**
It's out now.

### CODE REVIEW

**Review by gaborbernat — COMMENTED** [review]
Somethign seems broken.

**Comment by henryiii** [comment]
Is Python 3.11 triggering it's own deprecation warning on Windows?

```pytb
Traceback (most recent call last):
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\__main__.py", line 373, in main
    built = build_call(
            ^^^^^^^^^^^
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\__main__.py", line 233, in build_package_via_sdist
    sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\__main__.py", line 143, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\__main__.py", line 107, in _build_in_isolated_env
    with _IsolatedEnvBuilder() as env:
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\env.py", line 103, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\build\build\.tox\py311\Lib\site-packages\build\env.py", line 265, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True, symlinks=symlinks).create(path)
  File "C:\hostedtoolcache\windows\Python\3.11.0\x64\Lib\venv\__init__.py", line 74, in create
    self.setup_python(context)
  File "C:\hostedtoolcache\windows\Python\3.11.0\x64\Lib\venv\__init__.py", line 321, in setup_python
    copier(src, os.path.join(binpath, suffix))
  File "C:\hostedtoolcache\windows\Python\3.11.0\x64\Lib\venv\__init__.py", line 257, in symlink_or_copy
    if sysconfig.is_python_build(True) or not os.path.isfile(srcfn):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.0\x64\Lib\sysconfig.py", line 222, in is_python_build
    warnings.warn("check_home argument is deprecated and ignored.",
DeprecationWarning: check_home argument is deprecated and ignored.

ERROR check_home argument is deprecated and ignored.
```

**Comment by henryiii** [comment]
We would have caught the CPython bug before release if we had Windows 3.11 testing turned on, but we didn't because of - time I guess. Now 3.11.0 has the warning bug.

**Comment by nanonyme** [comment]
@henryiii did you already file a bug against CPython?

**Comment by henryiii** [comment]
Yes, bug https://github.com/python/cpython/issues/98741, PR https://github.com/python/cpython/pull/98743, already merged, though not backported from master yet.

**Review by gaborbernat — APPROVED** [review]

**Comment by hugovk** [comment]
Also add 3.10 and 3.11 here?

https://github.com/pypa/build/blob/b1acadc25702fe055cc7434d16ed2a0d766f094d/pyproject.toml#L60-L63

**Pull request merged**
