### PR TITLE
build: clarify that dependencies are build dependencies

### PR DESCRIPTION
**Pull request by abitrolly**
I would also change parameter `distribution` to `dist_type`, because it is not the actual package that is being meant here. Tell me if it is ok to do, and I'll add commits here.

### CODE REVIEW

**Comment by layday** [comment]
Let's rename the paramater in a separate PR - I'd also like to change its type to `Literal['sdist', 'wheel']` wherever it's used.

You need to update the tests.

**Comment by layday** [comment]
pre-commit.ci autofix

**Comment by abitrolly** [comment]
Squashed.

**Review by FFY00 — APPROVED** [review]
Thanks!

**Pull request merged**
