### PR TITLE
tests: support setuptools v69.0.3+

### PR DESCRIPTION
**Pull request by henryiii**
Fix for setuptools v69.0.3. Metadata is now stored as the user entered it.

### CODE REVIEW

**Comment by layday** [comment]
It looks like 69.0.2 is being installed on Python 3.11 and below for whatever reason. 3.11-tox on Ubuntu:

```
installed packages of interest: build==1.0.3 filelock==3.13.1 packaging==23.2 pip==23.3.1 pyproject_hooks==1.0.0 setuptools==69.0.2 wheel==0.42.0
```

The project builder tests also need fixing.

**Comment by layday** [comment]
Let's stop seeding setuptools and wheel, there's something funky going on there.

**Review by gaborbernat — APPROVED** [review]

**Review by layday — APPROVED** [review]

**Comment by henryiii** [comment]
I'm confused, why is:

```
does not appear to be a Python project: no pyproject.toml or setup.py
```

Showing up now, and only in the Windows < 3.10 min jobs? Setuptools doesn't even support 3.7 anymore, so how it breaking?

**Comment by henryiii** [comment]
Ahh this has been broken for a long time. I can go back at least four months and still see it. The problem (based on a different failure in an old log) is that pyproject.toml isn't being included in the SDist. Guessing it might be related to setuptools_scm pulling it in, where as now it's not.

**Comment by layday** [comment]
pyproject.toml should be included by default though? We shouldn't be needing a manifest for that.

**Comment by henryiii** [comment]
This is a min-version test, so it's using a really old setuptools, which I'm thinking might be missing pyproject.toml from the default includes. Just having a file finder (like setuptools_scm) present in the environment changes the include rules, so it seemed like a reasonable possibility.

It doesn't seem to have fixed it, so I think I was probably wrong.

**Comment by layday** [comment]
Theses errors only appear on Windows which leads me to believe it's an issue with DOS-encoded paths. No idea why it's only been happening recently.

**Comment by henryiii** [comment]
It is very suspicious that v43 was the one that added `pyproject.toml` to the default includes. https://setuptools.pypa.io/en/latest/history.html#id832 And setuptools is used for 3.7-3.9 min version tests.

**Comment by henryiii** [comment]
Ahh, I messed up the syntax, I wrote a MANIFEST, not a MANIFEST.in, but called it the latter.

**Comment by layday** [comment]
Ah, you've got a type, it's `METADATA.in`, should be `MANIFEST.in`. Looks like setup.cfg is being bundled but not pyproject.toml.

**Comment by wuch-g2v** [comment]
<details>
<summary>Looks like I just hit the same issue</summary>

```console
+ /usr/bin/pytest -ra -m 'not network'
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.0.0, pluggy-1.3.0
installed packages of interest: build==1.0.3 filelock==3.13.1 packaging==23.2 pip==24.0 pyproject_hooks==1.0.0 setuptools==69.1.0 tomli==2.0.1 virtualenv==20.25.0 wheel==0.42.0
rootdir: /home/tkloczko/rpmbuild/BUILD/build-1.0.3
configfile: pyproject.toml
testpaths: tests
plugins: mock-3.12.0, rerunfailures-12.0
collected 158 items / 10 deselected / 148 selected

tests/test_env.py ..ss...............                                    [ 12%]
tests/test_main.py ....................................                  [ 37%]
tests/test_main_helpers.py .                                             [ 37%]
tests/test_module.py ..                                                  [ 39%]
tests/test_projectbuilder.py ........................................... [ 68%]
FF.............                                                          [ 78%]
tests/test_util.py F                                                     [ 79%]
tests/test_integration.py sssssssssssssssssssssssssssssss                [100%]

=================================== FAILURES ===================================
________________________ test_metadata_path_no_prepare _________________________

tmp_dir = '/tmp/python-build-test-rt4kdrzu'
package_test_no_prepare = '/home/tkloczko/rpmbuild/BUILD/build-1.0.3/tests/packages/test-no-prepare'

    def test_metadata_path_no_prepare(tmp_dir, package_test_no_prepare):
        builder = build.ProjectBuilder(package_test_no_prepare)

        metadata = _importlib.metadata.PathDistribution(
            pathlib.Path(builder.metadata_path(tmp_dir)),
        ).metadata

>       assert metadata['name'] == 'test-no-prepare'
E       AssertionError: assert 'test_no_prepare' == 'test-no-prepare'
E
E         - test-no-prepare
E         ?     ^  ^
E         + test_no_prepare
E         ?     ^  ^

tests/test_projectbuilder.py:505: AssertionError
----------------------------- Captured stdout call -----------------------------
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying backend_no_prepare.py -> build/lib
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
copying build/lib/backend_no_prepare.py -> build/bdist.linux-x86_64/wheel
running install_egg_info
running egg_info
creating test_no_prepare.egg-info
writing test_no_prepare.egg-info/PKG-INFO
writing dependency_links to test_no_prepare.egg-info/dependency_links.txt
writing top-level names to test_no_prepare.egg-info/top_level.txt
writing manifest file 'test_no_prepare.egg-info/SOURCES.txt'
reading manifest file 'test_no_prepare.egg-info/SOURCES.txt'
writing manifest file 'test_no_prepare.egg-info/SOURCES.txt'
Copying test_no_prepare.egg-info to build/bdist.linux-x86_64/wheel/test_no_prepare-1.0.0-py3.8.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/test_no_prepare-1.0.0.dist-info/WHEEL
creating '/tmp/python-build-test-rt4kdrzu/.tmp-ajw6hw96/test_no_prepare-1.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'backend_no_prepare.py'
adding 'test_no_prepare-1.0.0.dist-info/METADATA'
adding 'test_no_prepare-1.0.0.dist-info/WHEEL'
adding 'test_no_prepare-1.0.0.dist-info/top_level.txt'
adding 'test_no_prepare-1.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
----------------------------- Captured stderr call -----------------------------
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

------------------------------ Captured log call -------------------------------
INFO     build:__init__.py:266 Getting metadata for wheel...
INFO     build:__init__.py:296 Building wheel...
_______________________ test_metadata_path_with_prepare ________________________

tmp_dir = '/tmp/python-build-test-jcsjwy09'
package_test_setuptools = '/home/tkloczko/rpmbuild/BUILD/build-1.0.3/tests/packages/test-setuptools'

    def test_metadata_path_with_prepare(tmp_dir, package_test_setuptools):
        builder = build.ProjectBuilder(package_test_setuptools)

        metadata = _importlib.metadata.PathDistribution(
            pathlib.Path(builder.metadata_path(tmp_dir)),
        ).metadata

>       assert metadata['name'] == 'test-setuptools'
E       AssertionError: assert 'test_setuptools' == 'test-setuptools'
E
E         - test-setuptools
E         ?     ^
E         + test_setuptools
E         ?     ^

tests/test_projectbuilder.py:516: AssertionError
----------------------------- Captured stdout call -----------------------------
running dist_info
creating /tmp/python-build-test-jcsjwy09/test_setuptools.egg-info
writing /tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/PKG-INFO
writing dependency_links to /tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/dependency_links.txt
writing top-level names to /tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/top_level.txt
writing manifest file '/tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/SOURCES.txt'
reading manifest file '/tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/SOURCES.txt'
writing manifest file '/tmp/python-build-test-jcsjwy09/test_setuptools.egg-info/SOURCES.txt'
creating '/tmp/python-build-test-jcsjwy09/test_setuptools-1.0.0.dist-info'
------------------------------ Captured log call -------------------------------
INFO     build:__init__.py:266 Getting metadata for wheel...
__________________________ test_wheel_metadata[False] __________________________

package_test_setuptools = '/home/tkloczko/rpmbuild/BUILD/build-1.0.3/tests/packages/test-setuptools'
isolated = False

    @pytest.mark.pypy3323bug
    @pytest.mark.parametrize('isolated', [False, pytest.param(True, marks=[pytest.mark.network, pytest.mark.isolated])])
    def test_wheel_metadata(package_test_setuptools, isolated):
        metadata = build.util.project_wheel_metadata(package_test_setuptools, isolated)

>       assert metadata['name'] == 'test-setuptools'
E       AssertionError: assert 'test_setuptools' == 'test-setuptools'
E
E         - test-setuptools
E         ?     ^
E         + test_setuptools
E         ?     ^

tests/test_util.py:15: AssertionError
------------------------------ Captured log call -------------------------------
INFO     build:__init__.py:266 Getting metadata for wheel...
=========================== short test summary info ============================
SKIPPED [1] tests/test_env.py:50: workaround for Apple Python
SKIPPED [1] tests/test_env.py:59: workaround for Debian/Ubuntu Python
SKIPPED [30] tests/test_integration.py:71: integration tests not run (no --run-integration flag)
SKIPPED [1] tests/test_integration.py: integration tests not run (no --run-integration flag)
FAILED tests/test_projectbuilder.py::test_metadata_path_no_prepare - Assertio...
FAILED tests/test_projectbuilder.py::test_metadata_path_with_prepare - Assert...
FAILED tests/test_util.py::test_wheel_metadata[False] - AssertionError: asser...
===== 3 failed, 112 passed, 33 skipped, 10 deselected in 83.97s (0:01:23) ======
```
</details>

If above is fixed by this MR Is it possible to release new version? 🤔

**Comment by henryiii** [comment]
This only affects our own tests?

**Comment by wuch-g2v** [comment]
It adds additional overhead on automated build to exclude those failing units 😋

**Pull request merged**
