### PR TITLE
tox: update docs environment to Python 3.9

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Review by webknjaz — COMMENTED** [review]
How about also updating `.readthedocs.yml`?

**Comment by webknjaz** [comment]
FYI I noticed that the docs job fails for an unrelated reason. This PR https://github.com/pypa/build/pull/235 should fix that.

**Comment by layday** [comment]
Does RTD support 3.9? Otherwise we should probably keep them in sync?

**Comment by gaborbernat** [comment]
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image says not yet

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Yeah, actually wait with this PR until readthedocs supports it.

**Comment by webknjaz** [comment]
> [docs.readthedocs.io/en/stable/config-file/v2.html#build-image](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image) says not yet

Those docs are often out-of-date but it seems you're right: it was added to the testing image just two weeks ago — https://github.com/readthedocs/readthedocs-docker-images/commit/3c6e81fa67d8cfd833fa86faf2d138f6e992ea16.

**Pull request closed without merging**
