### PR TITLE
build: rename get_dependencies to get_requires

### LINKED ISSUE #182: Rename `ProjectBuilder.get_dependencies`
Reading https://github.com/pypa/build/issues/181#issuecomment-721579088, I think this method's name is ambiguous and should be renamed to e.g. `get_backend_dependencies`.  Would there be any objections?

### PR DESCRIPTION
**Pull request by FFY00**
Fixes #182

Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Comment by layday** [comment]
I think this adds more confusion instead of disambiguating between pyproject.toml and backend dependencies.  The methid name is still not qualified and now there are two terms used to describe the same concept (require and dependency).

**Comment by FFY00** [comment]
We can rename it to `build_system_dependencies`... Do you have any better proposal?

**Comment by layday** [comment]
* `declared_dependencies` iso `build_dependencies`
* `get_dependencies_from_backend` iso `get_dependencies`

**Comment by FFY00** [comment]
>     * `declared_dependencies` iso `build_dependencies`

Why `declared_dependencies`? Both are declared, I think `build_system_dependencies` is clearer. 

>     * `get_dependencies_from_backend` iso `get_dependencies`

I personally don't really see a need to call it `get_dependencies_from_backend` instead of `get_dependencies`, given that it is a callable and the other is an attribute, but if others feel that this is needed, I am okay with changing it.

> We could use "requires" for both of these if we want to align them with the PEPs.

Sure.

**Comment by layday** [comment]
> Why `declared_dependencies`? Both are declared, I think `build_system_dependencies` is clearer.

`get_requires` is dynamic.  When you call `get_requires_for_build_wheel` on setuptools and it returns `["wheel"]`, where is `"wheel"` declared?

> I personally don't really see a need to call it `get_dependencies_from_backend` instead of `get_dependencies`, given that it is a callable and the other is an attribute, but if others feel that this is needed, I am okay with changing it.

That would provide perhaps the slightest hint that one's coming from the backend and the other from `pyproject.toml`, based purely on programmer intuition that a backend call is less likely to be a property.

**Comment by layday** [comment]
If we're adopting the term 'requires' (obscure as it might be), we could then simply shorten the hook name to `get_requires_for_build("sdist_or_wheel")`. This should be fairly unambiguous to anybody familiar with PEP 517, reads nicely and would also mirror the `build` method, cf. `build("sdist_or_wheel")`.  `build_system_requires` uses the exact same terms found in `pyproject.toml` and would be OK with me, instead of `declared_requires`.

**Comment by FFY00** [comment]
I would like to go for `get_requires_for_build` and `build_system_requires`.

**Comment by layday** [comment]
Sounds good to me!

**Comment by FFY00** [comment]
Done. On top of #296 and #297 to avoid conflicts, should go in after both of them. Only the last two commits are relevant.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
