### PR TITLE
Drop Python 3.6

### PR DESCRIPTION
**Pull request by layday**
3.6 reached its EOL in Dec of last year and our main dependencies (pep517 and packaging) have already dropped support for it.

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Comment by henryiii** [comment]
What about upgrading pre-commit's pyupgrade flag?

**Comment by layday** [comment]
Thanks, I've also updated black's targets and removed 3.6 from the tox matrix. I think that's all the 3.6 references 😅

**Comment by layday** [comment]
No clue why the docs are failing.

**Comment by layday** [comment]
I'm taking these logging line checks out, they are a major nuisance to have to update with every minor change that we make.

**Comment by layday** [comment]
> No clue why the docs are failing.

https://github.com/sphinx-doc/sphinx/issues/9275#issuecomment-1312782811

I just silenced the error for now, it doesn't look like we can link to `PackageMetadata` from the stdlib.

**Comment by layday** [comment]
@FFY00 Please take a look if you have time :)

**Review by FFY00 — APPROVED** [review]
Looks good. Thanks @layday!

Could you just fix the title of the first two commits before merging?

**Comment by layday** [comment]
Yeah, I just wasn't sure what prefix would be appropriate. `meta:` and `multiple:`, or maybe `chore:`?

**Comment by FFY00** [comment]
I would do `meta:` and `build:`, respectively.

**Comment by layday** [comment]
You'll have to remove the 3.6 tests from the main branch protection rules, BTW.

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
Done.

**Comment by henryiii** [comment]
I’d like to add a “pass” job so we don’t have to keep changing this in the future.

**Pull request merged**
