### PR TITLE
chore: bump to 1.0.1.post1 since 1.0.1 seems to be taken

### PR DESCRIPTION
**Pull request by henryiii**
It seems there was a previous build 1.0.1 release. Without knowing what files the old project had, we are kind of stuck in this try, try again game.

Another good reason to move to CalVer, IMO. :)

### CODE REVIEW

**Comment by henryiii** [comment]
Followup to #677. I'm not sure this is the actual issue, though, since the following query:

```sql
SELECT filename
FROM `bigquery-public-data.pypi.distribution_metadata`
WHERE name = "build"
```

produces

```json
[{
  "filename": "build-0.1.0-py2.py3-none-any.whl"
}, {
  "filename": "build-0.0.2.tar.gz"
}, {
  "filename": "build-0.0.3.1.tar.gz"
}, {
  "filename": "build-0.0.4.tar.gz"
}, {
  "filename": "build-0.0.4-py2.py3-none-any.whl"
}, {
  "filename": "build-0.0.2-py2.py3-none-any.whl"
}, {
  "filename": "build-0.0.3.1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.8.0-py3-none-any.whl"
}, {
  "filename": "build-0.8.0.tar.gz"
}, {
  "filename": "build-0.6.0.tar.gz"
}, {
  "filename": "build-0.6.0-py3-none-any.whl"
}, {
  "filename": "build-0.6.1.tar.gz"
}, {
  "filename": "build-0.6.1-py3-none-any.whl"
}, {
  "filename": "build-0.6.0.post1-py3-none-any.whl"
}, {
  "filename": "build-0.6.0.post1.tar.gz"
}, {
  "filename": "build-0.3.1.tar.gz"
}, {
  "filename": "build-0.3.1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.3.1.post1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.3.1.post1.tar.gz"
}, {
  "filename": "build-0.0.1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.4.0-py2.py3-none-any.whl"
}, {
  "filename": "build-0.4.0.tar.gz"
}, {
  "filename": "build-0.3.0.tar.gz"
}, {
  "filename": "build-0.3.0-py2.py3-none-any.whl"
}, {
  "filename": "build-0.7.0-py3-none-any.whl"
}, {
  "filename": "build-0.7.0.tar.gz"
}, {
  "filename": "build-0.9.0-py3-none-any.whl"
}, {
  "filename": "build-0.9.0.tar.gz"
}, {
  "filename": "build-0.2.0-py2.py3-none-any.whl"
}, {
  "filename": "build-0.2.0.tar.gz"
}, {
  "filename": "build-0.2.1.tar.gz"
}, {
  "filename": "build-0.2.1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.1.0.tar.gz"
}, {
  "filename": "build-1.0.0-py3-none-any.whl"
}, {
  "filename": "build-1.0.0.tar.gz"
}, {
  "filename": "build-0.0.1.tar.gz"
}, {
  "filename": "build-0.10.0-py3-none-any.whl"
}, {
  "filename": "build-0.10.0.tar.gz"
}, {
  "filename": "build-0.5.0.tar.gz"
}, {
  "filename": "build-0.5.0-py2.py3-none-any.whl"
}, {
  "filename": "build-0.5.1-py2.py3-none-any.whl"
}, {
  "filename": "build-0.5.1.tar.gz"
}]
```

Which doesn't seem to the a problem.

**Review by gaborbernat — CHANGES_REQUESTED** [review]
This is not the problem. See https://pypi.org/simple/build there's no 1.0.1.

**Comment by henryiii** [comment]
It's too old, this is from @di:

```
warehouse=> select action, submitted_date from journals where name='build' and action ilike 'add %';
                         action                          |       submitted_date
---------------------------------------------------------+----------------------------
 add Owner benjamin.hodgson                              | 2015-08-07 12:55:26
 add source file build-1.0.zip                           | 2015-08-07 12:55:40
 add 3.4 file build-1.0-py3.4.egg                        | 2015-08-07 12:55:44
 add 3.4 file build-1.0-cp34-none-win32.whl              | 2015-08-07 12:55:48
 add source file build-1.0.1.zip                         | 2015-08-07 14:20:59
 add 3.4 file build-1.0.1-py3-none-any.whl               | 2015-08-07 14:21:01
 add 3.4 file build-1.0.1-py3.4.egg                      | 2015-08-07 14:21:05
 add source file build-1.0.2.zip                         | 2015-08-07 15:09:17
 add 3.4 file build-1.0.2-py3.4.egg                      | 2015-08-07 15:09:25
 add 3.4 file build-1.0.2-py3-none-any.whl               | 2015-08-07 15:09:33
```

So we'll need `.post1` for 1.0.2 as well if we make one.

**Comment by gaborbernat** [comment]
Who uploaded 1.0.1 or 1.0.2?

**Comment by layday** [comment]
PyPI is picking up a 1.0.1 release from an older "build" project presumably.

**Comment by gaborbernat** [comment]
Still feels a bug in pypi, is 1.0 to 1.0.2 the only builds then we need to worry about?

**Comment by henryiii** [comment]
There was a project named "build" that was deleted to give us the name. It had two releases, on the same day in 2015, 1.0.1 and 1.0.2. We can either do 1.0.3 or 1.0.1.post1. We've done .post1 twice before.

This is a security feature in PyPI that is supposed to help projects that don't want to pin hashes. Though given person-in-the-middle attacks, post releases, and build numbers, I'm not sure it's really helping these projects except to give a false sense of security.

**Comment by gaborbernat** [comment]
Let's do 1.0.3 🤔 ?

**Comment by henryiii** [comment]
I like 1.0.3 best.

**Pull request closed without merging**
