### PR TITLE
main: improve console output

### PR DESCRIPTION
**Pull request by layday**

### CODE REVIEW

**Comment by layday** [comment]
Screenshot 2024-03-01 at 21 28 30

**Comment by henryiii** [comment]
Would it make sense to remove the bold on the package names? I think that would look a little more distinct:

Screenshot 2024-03-01 at 2 37 30 PM

**Comment by layday** [comment]
That makes sense, I've changed it.

**Comment by henryiii** [comment]
Much better, I think:

Screenshot 2024-03-01 at 3 55 57 PM

**Comment by layday** [comment]
Any thoughts on the verbosity option?

**Comment by henryiii** [comment]
Basically just passes through to the underlying pip? Seems fine.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
