### PR TITLE
docs: api: add build.util module

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Comment by FFY00** [comment]
Just realized I forgot this :sweat_smile:

**Comment by FFY00** [comment]
https://pypa-build--353.org.readthedocs.build/en/353/api.html#build-util-module

**Review by layday — APPROVED** [review]

**Review by gaborbernat — APPROVED** [review]

**Comment by layday** [comment]
Looks like the tests weren't skipped and are stuck now, I'll try to close and reopen.

**Comment by layday** [comment]
Okay, I assume this is because we use `paths-ignore` for the tests but they're not filtered out from the required check. Looks like you'll have to merge this one (and all doc PRs) manually.

**Pull request merged**
