### PR TITLE
tests: enable pytest strict mode

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by layday** [comment]
`test_colors_conflict` appears to be erroring because of `filterwarnings = error`.

**Review by gaborbernat — APPROVED** [review]

**Comment by layday** [comment]
Shouldn't the filtering be done in `test_colors_conflict` instead of the fixture?

**Comment by graingert** [comment]
@gaborbernat you pressed the wrong approval button, the CI needs to run xD

**Comment by layday** [comment]
I would prefer if we used a monkeypatching context. Remove the filter from the fixture and in `test_colors_conflict`:

```py
with monkeypatch.context() as m:
    m.setenv('NO_COLOR', '')
    ,.setenv('FORCE_COLOR', '')

    with pytest.warns(Warning, match='Both NO_COLOR and FORCE_COLOR environment variables are set, disabling color'):
        importlib.reload(build.__main__)
```

**Comment by graingert** [comment]
> I would prefer if we used a monkeypatching context. Remove the filter from the fixture and in `test_colors_conflict`:
> 
> ```python
> with monkeypatch.context() as m:
>     m.setenv('NO_COLOR', '')
>     m.setenv('FORCE_COLOR', '')
> 
>     with pytest.warns(Warning, match='Both NO_COLOR and FORCE_COLOR environment variables are set, disabling color'):
>         importlib.reload(build.__main__)
> ```

That would make sense in a test case, but not in the cleanup

**Comment by layday** [comment]
That is for the test case.

**Comment by graingert** [comment]
The importlib reload will happen again in the fixture and raise a new warning

**Comment by layday** [comment]
That's what the monkeypatch context is there for, it won't raise a warning outside of the context.

**Comment by graingert** [comment]
Oh! I see what you mean now

**Review by layday — APPROVED** [review]

**Comment by layday** [comment]
Great, thanks! Will let @FFY00 take a look before merging.

**Review by FFY00 — APPROVED** [review]
LGTM, thanks! :blush:

**Pull request merged**
