### PR TITLE
Override leaky env vars

### PR DESCRIPTION
**Pull request by layday**
On top of #361.

### CODE REVIEW

**Review by FFY00 — COMMENTED** [review]
Overall looks good but we are blocked by #361.

**Comment by adamjstewart** [comment]
Fixes #266

**Comment by layday** [comment]
It fixes one particular cause of that error.  I think that we should provide a better message for when pip can't be found, that's what #266 ought to fix.

**Comment by gaborbernat** [comment]
@layday shall we close this now, or you want to rebase it?

**Comment by layday** [comment]
This is blocked by #361, no point rebasing before #361 is resolved.

**Comment by gaborbernat** [comment]
> This is blocked by #361,

Approved.

**Comment by layday** [comment]
Feel free to cherry-pick whatever makes sense.

**Comment by salotz-sitx** [comment]
Seeing as #361 isn't going to be merged should this be reopened? Or am I missing what the decision is?

**Comment by FFY00** [comment]
The problem is lack of maintainer time. I was unable to review this in time, so @layday decided to close it. I hope to pick it up in the next few months.

**Comment by henryiii** [comment]
There's somewhat of a bottleneck waiting on @FFY00 to review #361. I think the plan is still to go with #361, we even had an approval for it.

**Comment by salotz-sitx** [comment]
Got it, thank you!

**Comment by layday** [comment]
It's nothing personal, just having PRs linger fills me with a weird sort of anxiety.

**Comment by salotz-sitx** [comment]
Whatever makes you more productive :) I just wanted to know if I should keep following along or not.

**Comment by henryiii** [comment]
We can reopen as needed, so they aren't just sitting open. :) I'm also happy to volunteer to rebase as needed. It's just @FFY00 is the most qualified to review.

**Comment by salotz-sitx** [comment]
For anyone looking for workarounds coming from the Spack world.

I install Python and all my run time dependencies using Spack but for development tools (like `build`) I typically just install them with `pip` in a venv on top of the Spack virtual environment. Installing `build` alone I get this problem, but `build[virtualenv]` works for me in this case.

**Comment by adamjstewart** [comment]
Spack should no longer have this issue in the latest release. I added a patch to unset `PYTHONPATH` to avoid this issue: https://github.com/spack/spack/pull/28562

**Comment by adamjstewart** [comment]
Was this issue ever fixed in main or is a patch still needed?

**Comment by layday** [comment]
Still needed.

**Comment by adamjstewart** [comment]
According to #470, the recommended way to bootstrap build is to install it from a wheel. How do I patch a wheel?

**Comment by adamjstewart** [comment]
Or is there a way to use build to build itself?

**Comment by henryiii** [comment]
#361 was replaced by #537, so can't this be redone on top of that?

**Comment by layday** [comment]
These are the two changes unique to this PR:

* https://github.com/pypa/build/pull/406/commits/38099ad07636311d5ca8e810baf12b952b8f2568
* https://github.com/pypa/build/pull/406/commits/fe1e678317e9f0ea4ce33689a287e4fb6662481b

**Comment by adamjstewart** [comment]
The specific bug we're facing is #266, so once #266 is solved we'll no longer need to patch. [This patch](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-build/isolation.patch) was sufficient for us to solve the issue, but I'm not sure how hacky that is. It's also outdated, see https://github.com/spack/spack/pull/35326 for my latest patch.

**Pull request closed without merging**
