### PR TITLE
tests: fix for PEP 685 in packaging 22

### PR DESCRIPTION
**Pull request by henryiii**
Support Packaging 22.

### CODE REVIEW

**Comment by layday** [comment]
If packaging doesn't normalise dependency names when stringifying dependencies, why does it normalise their extras?  Anyway, the easiest thing to do here is to replace all underscores in extra names in the tests with hyphens.

**Comment by layday** [comment]
This only affects extra names in markers, BTW, not square bracket extra selectors.

**Comment by nanonyme** [comment]
That sounds inconsistent enough to definitely warrant an upstream issue.

**Comment by henryiii** [comment]
But those have to be consistent to make older packaging pass, since older packaging does not consider `a-b` to match `a_b`.

**Comment by henryiii** [comment]
RtD is misbehaving today, also in pypa/packaging.

**Review by layday — APPROVED** [review]

**Comment by henryiii** [comment]
> RtD supposed to work from forks at all?

I think so. Never had a problem before.

**Comment by henryiii** [comment]
Passes now, so yes. :)

**Pull request merged**
