### PR TITLE
misc: add @layday to the code owners

### PR DESCRIPTION
**Pull request by gaborbernat**
We should have done this when we invited @layday to be a maintainer 👏🏻

### CODE REVIEW

**Comment by FFY00** [comment]
Eh, it's up to them. If they want to be always pinged for review, they can add themselves. If they just want to be pinged on a certain part of the code, they can do that too.

cc @henryiii

**Review by FFY00 — APPROVED** [review]

**Comment by layday** [comment]
Happy to be added to owners, thanks.

**Comment by henryiii** [comment]
> cc @henryiii

I'm not going to be much use for the next two weeks 👶, maybe after that?

**Comment by henryiii** [comment]
The branch is sitting around still, would the auto-delete branches on merges option be a good idea, to keep things tidy?

**Pull request merged**
