### PR TITLE
Remove py workaround

### PR DESCRIPTION
**Pull request by hugovk**
https://github.com/pytest-dev/py/issues/273 has now been released so we can remove the workaround.

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Review by henryiii — APPROVED** [review]

**Comment by layday** [comment]
I don't want to re-run an untold number of jobs because of one flake.  Can we force merge this?

**Comment by hugovk** [comment]
(Aside: GitHub will soon allow re-running single jobs: https://github.com/github/roadmap/issues/271)

**Comment by layday** [comment]
It's always something new isn't it? Now that packaging is fixed the Windows 3.9 tests are failing.

**Pull request merged**
