### PR TITLE
Only import importlib_metadata when needed

### PR DESCRIPTION
**Pull request by jmroot**
Similar to #395, this helps with bootstrap issues with python < 3.8.

### CODE REVIEW

**Comment by layday** [comment]
The `importlib_metadata` import was removed in #361 which is awaiting feedback.

**Comment by jmroot** [comment]
Ah, OK. Feel free to close then, unless the other PR is going to take a while (would be nice to get this in a release).

**Comment by layday** [comment]
I don't have an estimate, sorry.

**Comment by layday** [comment]
`test_pip_needs_upgrade_mac_os_11` needs fixing if you'd still like for this to be merged.

**Comment by jmroot** [comment]
I'm afraid I don't know what the test that is now failing is even supposed to be testing, let alone how to fix it.

**Comment by henryiii** [comment]
Ahh, that’s our self checking source test. It’s a pain. Basically you just have to adjust the line numbers if they change. We improved it a little, but it’s still very sensitive to any source changes. I can fix it later if that’s easiest.

**Comment by jmroot** [comment]
@henryiii CI passed; is there any remaining reason not to approve this?

**Review by gaborbernat — APPROVED** [review]

**Review by henryiii — APPROVED** [review]
No, I just forgot to return. Gentle reminders always appreciated!

**Pull request merged**
