### PR TITLE
docs: fix release date

### PR DESCRIPTION
**Pull request by henryiii**

### CODE REVIEW

**Review by layday — APPROVED** [review]

**Review by FFY00 — APPROVED** [review]
Oops, sorry.

**Comment by layday** [comment]
You'll need to force-merge this since the Win 3.6 job errored.

**Comment by henryiii** [comment]
Looks like a network issue, so I can try restarting the failed job.

**Comment by layday** [comment]
I forgot you can run jobs selectively now 😄

**Pull request merged**
