### PR TITLE
Add code owners file

### PR DESCRIPTION
**Pull request by gaborbernat**
For automatic review request notification.

Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>

### CODE REVIEW

**Review by FFY00 — APPROVED** [review]

**Comment by gaborbernat** [comment]
```
docs/readthedocs.org:python-build Expected — Waiting for status to be reported
```

😢 may need to reset the connection 🤔

**Comment by FFY00** [comment]
I have removed the bad webhooks.

Note that the correct hook still runs.
```
 docs/readthedocs.org:pypa-build — Read the Docs build succeeded! 
```

**Comment by FFY00** [comment]
Ah, nvm... Nothing is running, it is just marked as a required job.

**Comment by FFY00** [comment]
Fixed!

**Pull request merged**
